name: Microservice CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This job "calls" the reusable template we created.
  call-reusable-workflow:
    # Path to the shared template: repository/path/to/file@branch
    uses: victorrumanski/my-spring-service/.github/workflows/reusable-ci.yml@main
    with:
      # We pass the image name as an input to the template.
      image_name: ${{ github.repository }}
    secrets: inherit # Pass the GITHUB_TOKEN automatically
